project:
  type: website
  output-dir: docs

website:
  title: "Anya Nazarenko"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - grants.qmd
      - about.qmd
      - posts.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

