---
title: "Grants"
---

## Funding: Grants, Proposals, and Contracts

***Cleveland Police Co-Responder Program*** (2019-MO-BX-0048), United States Department of Justice, Office of Justice Programs, Bureau of Justice Programs through the City of Cleveland Division of Police, \$210,000 (10/1/2019 to 03/31/2023). Role: Research Assistant.

***Cuyahoga County Early Jail Diversion Program*** (6H79SM080576-01M001), United States Department of Health and Human Services Substance Abuse Mental Health Services Administration (SAMHSA) Center for Mental Health Services (CMHS) through the Cuyahoga County Addiction Drug Abuse Mental Health Services Board, \$330,000 (9/10/2019-8/31/2023). Role: Research Assistant.

***The Centers for Families and Children Community Mental Health Center Project*** (1H79SM085587-01), United States Department of Health and Human Services, Substance Abuse and Mental Health Services Administration (SAMSHA) through The Centers for Families and Children, \$700,000 (10/1/2021-9/30/2023). Role: Research Assistant.

***Crossroads Health Certified Community Behavior Health Center Project*** (1H79SM083073-01), United States Department of Health and Human Services, Substance Abuse and Mental Health Services Administration (SAMSHA) through Crossroads Health Lake County Adolescent Counseling Service, \$500,000 (2/15/2021-2/14/2023). Role: Research Assistant.

***The Centers for Families and Children Certified Community Behavior Health Center Project*** (1H79SM083063-01), United States Department of Health and Human Services, Substance Abuse and Mental Health Services Administration (SAMSHA) through The Centers for Families and Children, \$451,000 (2/15/2021-2/14/2023). Role: Research Assistant.

***Cuyahoga County Assisted Outpatient Treatment (AOT) Pilot Project*** (1H79SM063540-01). United States Department of Health and Human Services Substance Abuse Mental Health Services Administration (SAMHSA) Center for Substance Abuse (CASP) through the Cuyahoga County Addiction Drug Abuse Mental Health Services Board, \$800,000 (9/30/2016-9/29/2020). Role: Research Assistant.
